### ISSUE TITLE
Peer review - Code

### ISSUE THREAD

**Issue by victorboucher** [lisaoude/artist-guesser#9]
The structure of your project looks good! You are splitting up your route(s) and have your router in a separate file. Your views and static files are also split up, its looking nice but here are some things that you could improve on:
- You could add all your source files in a 'src' directory, you could just place this in your root directory and put everything in there that builds the project. This helps you keep your workflow clean since you also have some config files in your root directory. Finding the right files would get easier since everything that you need to edit will be located in this 'src' directory.
- You could add two folders in your public directory for your 'scripts' and 'styles'. If you add any more css or js files in the future, this will give you a better structure.
- You could (actually should) install Nodemon, otherwise you would have to restart your app every time you make a change in the backend code.
- I almost wanted to tell you that you should add .DS_Store in your gitignore but since you are on Windows this is not necessary :^)
- Your code is looking clean, its not a lot but everything that you have written looks good. 
- In my opinion it is good practice to put this line at the very top of your app.js file, if you import anything above it that needs anything from the .env file, it wont work. But since you are only importing 'externals' above it, it doesn't matter that much. https://github.com/lisaoude/artist-guesser/blob/646ec20370b8a452b7cf5a2caf452f2b25f3aa3f/app.js#L11
- You could split up all your different socket functions in a 'sockets' folder. Then import them into a single file all together to keep your code clean. I've not done this myself yet, but I will do that soon since my code became a mess recently 😄 .

Nice start, keep up the good work! 🥇

**Comment by lisaoude** [comment]
Thanks for the feedback! 😄 

---

I won't put my building files in to a 'src' folder, because I'd need to change quite some things to let all files still communicate in the right way with each other. However, I will keep this in mind for my next project!

---

## To Do:
- [x] Put scripts & styles in their own respective folders
- [x] Install nodemon for the project (now installed globally)
- [x] Put require for .env at the top of my file

Could have
- [ ] Split socket functions in to separate files & import into one
